export const mockData = {data:[
	{
		transaction_date: "2025-03-06",
		ticker: "IBM",
		executive: "FEHRING, NICOLAS A.",
		executive_title: "VP, Controller",
		security_type: "Common Stock",
		acquisition_or_disposal: "D",
		shares: "400.0",
		share_price: "0.0",
	},
	{
		transaction_date: "2025-03-03",
		ticker: "IBM",
		executive: "THOMAS, ROBERT DAVID",
		executive_title: "Senior Vice President",
		security_type: "Common Stock",
		acquisition_or_disposal: "D",
		shares: "26543.0",
		share_price: "253.0098",
	},
	{
		transaction_date: "2025-02-28",
		ticker: "IBM",
		executive: "FARR, DAVID N",
		executive_title: "Director",
		security_type: "Common Stock",
		acquisition_or_disposal: "A",
		shares: "1200.0",
		share_price: "249.0",
	},
	{
		transaction_date: "2025-02-21",
		ticker: "IBM",
		executive: "KRISHNA, ARVIND",
		executive_title: "Director, Chairman, President & CEO",
		security_type: "Common Stock",
		acquisition_or_disposal: "D",
		shares: "2584.0",
		share_price: "262.925",
	},
	{
		transaction_date: "2025-02-21",
		ticker: "IBM",
		executive: "KRISHNA, ARVIND",
		executive_title: "Director, Chairman, President & CEO",
		security_type: "Common Stock",
		acquisition_or_disposal: "A",
		shares: "5163.0",
		share_price: "0.0",
	},
	{
		transaction_date: "2025-02-21",
		ticker: "IBM",
		executive: "LAMOREAUX, NICKLE JACLYN",
		executive_title: "Senior Vice President",
		security_type: "Common Stock",
		acquisition_or_disposal: "A",
		shares: "1051.0",
		share_price: "0.0",
	},
	{
		transaction_date: "2025-02-21",
		ticker: "IBM",
		executive: "THOMAS, ROBERT DAVID",
		executive_title: "Senior Vice President",
		security_type: "Rst. Stock Unit",
		acquisition_or_disposal: "D",
		shares: "3116.0",
		share_price: "0.0",
	},
	{
		transaction_date: "2025-02-21",
		ticker: "IBM",
		executive: "THOMAS, ROBERT DAVID",
		executive_title: "Senior Vice President",
		security_type: "Rst. Stock Unit",
		acquisition_or_disposal: "D",
		shares: "2628.0",
		share_price: "0.0",
	},
	{
		transaction_date: "2025-02-21",
		ticker: "IBM",
		executive: "THOMAS, ROBERT DAVID",
		executive_title: "Senior Vice President",
		security_type: "Common Stock",
		acquisition_or_disposal: "D",
		shares: "1349.0",
		share_price: "262.925",
	},
	{
		transaction_date: "2025-02-21",
		ticker: "IBM",
		executive: "THOMAS, ROBERT DAVID",
		executive_title: "Senior Vice President",
		security_type: "Common Stock",
		acquisition_or_disposal: "A",
		shares: "2666.0",
		share_price: "0.0",
	},
	{
		transaction_date: "2025-02-21",
		ticker: "IBM",
		executive: "FEHRING, NICOLAS A.",
		executive_title: "VP, Controller",
		security_type: "Common Stock",
		acquisition_or_disposal: "A",
		shares: "394.0",
		share_price: "0.0",
	},
	{
		transaction_date: "2025-02-21",
		ticker: "IBM",
		executive: "FEHRING, NICOLAS A.",
		executive_title: "VP, Controller",
		security_type: "Common Stock",
		acquisition_or_disposal: "D",
		shares: "141.0",
		share_price: "262.925",
	},
	{
		transaction_date: "2025-02-21",
		ticker: "IBM",
		executive: "FEHRING, NICOLAS A.",
		executive_title: "VP, Controller",
		security_type: "Rst. Stock Unit",
		acquisition_or_disposal: "D",
		shares: "394.0",
		share_price: "0.0",
	},
	{
		transaction_date: "2025-02-21",
		ticker: "IBM",
		executive: "COHN, GARY D",
		executive_title: "Vice Chairman",
		security_type: "Rst. Stock Unit",
		acquisition_or_disposal: "D",
		shares: "2722.0",
		share_price: "0.0",
	},
	{
		transaction_date: "2025-02-21",
		ticker: "IBM",
		executive: "COHN, GARY D",
		executive_title: "Vice Chairman",
		security_type: "Rst. Stock Unit",
		acquisition_or_disposal: "D",
		shares: "2612.0",
		share_price: "0.0",
	},
	{
		transaction_date: "2025-02-21",
		ticker: "IBM",
		executive: "COHN, GARY D",
		executive_title: "Vice Chairman",
		security_type: "Rst. Stock Unit",
		acquisition_or_disposal: "D",
		shares: "2245.0",
		share_price: "0.0",
	},
	{
		transaction_date: "2025-02-21",
		ticker: "IBM",
		executive: "THOMAS, ROBERT DAVID",
		executive_title: "Senior Vice President",
		security_type: "Rst. Stock Unit",
		acquisition_or_disposal: "D",
		shares: "2666.0",
		share_price: "0.0",
	},
	{
		transaction_date: "2025-02-21",
		ticker: "IBM",
		executive: "LAMOREAUX, NICKLE JACLYN",
		executive_title: "Senior Vice President",
		security_type: "Common Stock",
		acquisition_or_disposal: "D",
		shares: "537.0",
		share_price: "262.925",
	},
	{
		transaction_date: "2025-02-21",
		ticker: "IBM",
		executive: "THOMAS, ROBERT DAVID",
		executive_title: "Senior Vice President",
		security_type: "Common Stock",
		acquisition_or_disposal: "D",
		shares: "1575.0",
		share_price: "262.925",
	},
	{
		transaction_date: "2025-02-21",
		ticker: "IBM",
		executive: "COHN, GARY D",
		executive_title: "Vice Chairman",
		security_type: "Common Stock",
		acquisition_or_disposal: "D",
		shares: "1242.0",
		share_price: "262.925",
	},
	{
		transaction_date: "2025-02-21",
		ticker: "IBM",
		executive: "COHN, GARY D",
		executive_title: "Vice Chairman",
		security_type: "Common Stock",
		acquisition_or_disposal: "A",
		shares: "2245.0",
		share_price: "0.0",
	},
	{
		transaction_date: "2025-02-21",
		ticker: "IBM",
		executive: "COHN, GARY D",
		executive_title: "Vice Chairman",
		security_type: "Common Stock",
		acquisition_or_disposal: "D",
		shares: "1445.0",
		share_price: "262.925",
	},
	{
		transaction_date: "2025-02-21",
		ticker: "IBM",
		executive: "THOMAS, ROBERT DAVID",
		executive_title: "Senior Vice President",
		security_type: "Common Stock",
		acquisition_or_disposal: "A",
		shares: "3116.0",
		share_price: "0.0",
	},
	{
		transaction_date: "2025-02-21",
		ticker: "IBM",
		executive: "THOMAS, ROBERT DAVID",
		executive_title: "Senior Vice President",
		security_type: "Common Stock",
		acquisition_or_disposal: "D",
		shares: "1327.0",
		share_price: "262.925",
	},
	{
		transaction_date: "2025-02-21",
		ticker: "IBM",
		executive: "THOMAS, ROBERT DAVID",
		executive_title: "Senior Vice President",
		security_type: "Common Stock",
		acquisition_or_disposal: "A",
		shares: "2628.0",
		share_price: "0.0",
	},
	{
		transaction_date: "2025-02-21",
		ticker: "IBM",
		executive: "COHN, GARY D",
		executive_title: "Vice Chairman",
		security_type: "Common Stock",
		acquisition_or_disposal: "A",
		shares: "2612.0",
		share_price: "0.0",
	},
	{
		transaction_date: "2025-02-21",
		ticker: "IBM",
		executive: "COHN, GARY D",
		executive_title: "Vice Chairman",
		security_type: "Common Stock",
		acquisition_or_disposal: "D",
		shares: "1506.0",
		share_price: "262.925",
	},
	{
		transaction_date: "2025-02-21",
		ticker: "IBM",
		executive: "COHN, GARY D",
		executive_title: "Vice Chairman",
		security_type: "Common Stock",
		acquisition_or_disposal: "A",
		shares: "2722.0",
		share_price: "0.0",
	},
	{
		transaction_date: "2025-02-21",
		ticker: "IBM",
		executive: "FEHRING, NICOLAS A.",
		executive_title: "VP, Controller",
		security_type: "Rst. Stock Unit",
		acquisition_or_disposal: "D",
		shares: "631.0",
		share_price: "0.0",
	},
	{
		transaction_date: "2025-02-21",
		ticker: "IBM",
		executive: "FEHRING, NICOLAS A.",
		executive_title: "VP, Controller",
		security_type: "Rst. Stock Unit",
		acquisition_or_disposal: "D",
		shares: "541.0",
		share_price: "0.0",
	},
	{
		transaction_date: "2025-02-21",
		ticker: "IBM",
		executive: "FEHRING, NICOLAS A.",
		executive_title: "VP, Controller",
		security_type: "Common Stock",
		acquisition_or_disposal: "D",
		shares: "225.0",
		share_price: "262.925",
	},
	{
		transaction_date: "2025-02-21",
		ticker: "IBM",
		executive: "FEHRING, NICOLAS A.",
		executive_title: "VP, Controller",
		security_type: "Common Stock",
		acquisition_or_disposal: "A",
		shares: "631.0",
		share_price: "0.0",
	},
	{
		transaction_date: "2025-02-21",
		ticker: "IBM",
		executive: "FEHRING, NICOLAS A.",
		executive_title: "VP, Controller",
		security_type: "Common Stock",
		acquisition_or_disposal: "D",
		shares: "193.0",
		share_price: "262.925",
	},
	{
		transaction_date: "2025-02-21",
		ticker: "IBM",
		executive: "FEHRING, NICOLAS A.",
		executive_title: "VP, Controller",
		security_type: "Common Stock",
		acquisition_or_disposal: "A",
		shares: "541.0",
		share_price: "0.0",
	},
	{
		transaction_date: "2025-02-21",
		ticker: "IBM",
		executive: "KAVANAUGH, JAMES J",
		executive_title: "Sr. VP and CFO",
		security_type: "Rst. Stock Unit",
		acquisition_or_disposal: "D",
		shares: "3575.0",
		share_price: "0.0",
	},
	{
		transaction_date: "2025-02-21",
		ticker: "IBM",
		executive: "KAVANAUGH, JAMES J",
		executive_title: "Sr. VP and CFO",
		security_type: "Common Stock",
		acquisition_or_disposal: "D",
		shares: "1442.0",
		share_price: "262.925",
	},
	{
		transaction_date: "2025-02-21",
		ticker: "IBM",
		executive: "KAVANAUGH, JAMES J",
		executive_title: "Sr. VP and CFO",
		security_type: "Common Stock",
		acquisition_or_disposal: "A",
		shares: "2877.0",
		share_price: "0.0",
	},
	{
		transaction_date: "2025-02-21",
		ticker: "IBM",
		executive: "KAVANAUGH, JAMES J",
		executive_title: "Sr. VP and CFO",
		security_type: "Common Stock",
		acquisition_or_disposal: "D",
		shares: "1792.0",
		share_price: "262.925",
	},
	{
		transaction_date: "2025-02-21",
		ticker: "IBM",
		executive: "KAVANAUGH, JAMES J",
		executive_title: "Sr. VP and CFO",
		security_type: "Common Stock",
		acquisition_or_disposal: "A",
		shares: "3575.0",
		share_price: "0.0",
	},
	{
		transaction_date: "2025-02-21",
		ticker: "IBM",
		executive: "KAVANAUGH, JAMES J",
		executive_title: "Sr. VP and CFO",
		security_type: "Common Stock",
		acquisition_or_disposal: "D",
		shares: "1694.0",
		share_price: "262.925",
	},
	{
		transaction_date: "2025-02-21",
		ticker: "IBM",
		executive: "KAVANAUGH, JAMES J",
		executive_title: "Sr. VP and CFO",
		security_type: "Common Stock",
		acquisition_or_disposal: "A",
		shares: "3380.0",
		share_price: "0.0",
	},
	{
		transaction_date: "2025-02-21",
		ticker: "IBM",
		executive: "KRISHNA, ARVIND",
		executive_title: "Director, Chairman, President & CEO",
		security_type: "Rst. Stock Unit",
		acquisition_or_disposal: "D",
		shares: "5613.0",
		share_price: "0.0",
	},
	{
		transaction_date: "2025-02-21",
		ticker: "IBM",
		executive: "KRISHNA, ARVIND",
		executive_title: "Director, Chairman, President & CEO",
		security_type: "Rst. Stock Unit",
		acquisition_or_disposal: "D",
		shares: "6123.0",
		share_price: "0.0",
	},
	{
		transaction_date: "2025-02-21",
		ticker: "IBM",
		executive: "KRISHNA, ARVIND",
		executive_title: "Director, Chairman, President & CEO",
		security_type: "Rst. Stock Unit",
		acquisition_or_disposal: "D",
		shares: "5163.0",
		share_price: "0.0",
	},
	{
		transaction_date: "2025-02-21",
		ticker: "IBM",
		executive: "KRISHNA, ARVIND",
		executive_title: "Director, Chairman, President & CEO",
		security_type: "Common Stock",
		acquisition_or_disposal: "D",
		shares: "2813.0",
		share_price: "262.925",
	},
	{
		transaction_date: "2025-02-21",
		ticker: "IBM",
		executive: "KRISHNA, ARVIND",
		executive_title: "Director, Chairman, President & CEO",
		security_type: "Common Stock",
		acquisition_or_disposal: "A",
		shares: "5613.0",
		share_price: "0.0",
	},
	{
		transaction_date: "2025-02-21",
		ticker: "IBM",
		executive: "KRISHNA, ARVIND",
		executive_title: "Director, Chairman, President & CEO",
		security_type: "Common Stock",
		acquisition_or_disposal: "D",
		shares: "3069.0",
		share_price: "262.925",
	},
	{
		transaction_date: "2025-02-21",
		ticker: "IBM",
		executive: "LAMOREAUX, NICKLE JACLYN",
		executive_title: "Senior Vice President",
		security_type: "Rst. Stock Unit",
		acquisition_or_disposal: "D",
		shares: "1600.0",
		share_price: "0.0",
	},
	{
		transaction_date: "2025-02-21",
		ticker: "IBM",
		executive: "LAMOREAUX, NICKLE JACLYN",
		executive_title: "Senior Vice President",
		security_type: "Rst. Stock Unit",
		acquisition_or_disposal: "D",
		shares: "1738.0",
		share_price: "0.0",
	},
	{
		transaction_date: "2025-02-21",
		ticker: "IBM",
		executive: "LAMOREAUX, NICKLE JACLYN",
		executive_title: "Senior Vice President",
		security_type: "Rst. Stock Unit",
		acquisition_or_disposal: "D",
		shares: "1051.0",
		share_price: "0.0",
	},
	{
		transaction_date: "2025-02-21",
		ticker: "IBM",
		executive: "LAMOREAUX, NICKLE JACLYN",
		executive_title: "Senior Vice President",
		security_type: "Common Stock",
		acquisition_or_disposal: "D",
		shares: "817.0",
		share_price: "262.925",
	},
	{
		transaction_date: "2025-02-21",
		ticker: "IBM",
		executive: "LAMOREAUX, NICKLE JACLYN",
		executive_title: "Senior Vice President",
		security_type: "Common Stock",
		acquisition_or_disposal: "A",
		shares: "1600.0",
		share_price: "0.0",
	},
	{
		transaction_date: "2025-02-21",
		ticker: "IBM",
		executive: "LAMOREAUX, NICKLE JACLYN",
		executive_title: "Senior Vice President",
		security_type: "Common Stock",
		acquisition_or_disposal: "D",
		shares: "888.0",
		share_price: "262.925",
	},
	{
		transaction_date: "2025-02-21",
		ticker: "IBM",
		executive: "KAVANAUGH, JAMES J",
		executive_title: "Sr. VP and CFO",
		security_type: "Rst. Stock Unit",
		acquisition_or_disposal: "D",
		shares: "2877.0",
		share_price: "0.0",
	},
	{
		transaction_date: "2025-02-21",
		ticker: "IBM",
		executive: "LAMOREAUX, NICKLE JACLYN",
		executive_title: "Senior Vice President",
		security_type: "Common Stock",
		acquisition_or_disposal: "A",
		shares: "1738.0",
		share_price: "0.0",
	},
	{
		transaction_date: "2025-02-21",
		ticker: "IBM",
		executive: "KAVANAUGH, JAMES J",
		executive_title: "Sr. VP and CFO",
		security_type: "Rst. Stock Unit",
		acquisition_or_disposal: "D",
		shares: "3380.0",
		share_price: "0.0",
	},
	{
		transaction_date: "2025-02-21",
		ticker: "IBM",
		executive: "KRISHNA, ARVIND",
		executive_title: "Director, Chairman, President & CEO",
		security_type: "Common Stock",
		acquisition_or_disposal: "A",
		shares: "6123.0",
		share_price: "0.0",
	},
	{
		transaction_date: "2025-02-18",
		ticker: "IBM",
		executive: "FEHRING, NICOLAS A.",
		executive_title: "VP, Controller",
		security_type: "Emp. Stock Option (right to buy)",
		acquisition_or_disposal: "A",
		shares: "7432.0",
		share_price: "0.0",
	},
	{
		transaction_date: "2025-02-18",
		ticker: "IBM",
		executive: "THOMAS, ROBERT DAVID",
		executive_title: "Senior Vice President",
		security_type: "Rst. Stock Unit",
		acquisition_or_disposal: "A",
		shares: "10197.0",
		share_price: "0.0",
	},
	{
		transaction_date: "2025-02-18",
		ticker: "IBM",
		executive: "THOMAS, ROBERT DAVID",
		executive_title: "Senior Vice President",
		security_type: "Emp. Stock Option (right to buy)",
		acquisition_or_disposal: "A",
		shares: "40786.0",
		share_price: "0.0",
	},
	{
		transaction_date: "2025-02-18",
		ticker: "IBM",
		executive: "ROBINSON, ANNE",
		executive_title: "Senior Vice President",
		security_type: "Rst. Stock Unit",
		acquisition_or_disposal: "A",
		shares: "6889.0",
		share_price: "0.0",
	},
	{
		transaction_date: "2025-02-18",
		ticker: "IBM",
		executive: "ROBINSON, ANNE",
		executive_title: "Senior Vice President",
		security_type: "Emp. Stock Option (right to buy)",
		acquisition_or_disposal: "A",
		shares: "27553.0",
		share_price: "0.0",
	},
	{
		transaction_date: "2025-02-18",
		ticker: "IBM",
		executive: "LAMOREAUX, NICKLE JACLYN",
		executive_title: "Senior Vice President",
		security_type: "Rst. Stock Unit",
		acquisition_or_disposal: "A",
		shares: "6345.0",
		share_price: "0.0",
	},
	{
		transaction_date: "2025-02-18",
		ticker: "IBM",
		executive: "LAMOREAUX, NICKLE JACLYN",
		executive_title: "Senior Vice President",
		security_type: "Emp. Stock Option (right to buy)",
		acquisition_or_disposal: "A",
		shares: "25378.0",
		share_price: "0.0",
	},
	{
		transaction_date: "2025-02-18",
		ticker: "IBM",
		executive: "KAVANAUGH, JAMES J",
		executive_title: "Sr. VP and CFO",
		security_type: "Rst. Stock Unit",
		acquisition_or_disposal: "A",
		shares: "10877.0",
		share_price: "0.0",
	},
	{
		transaction_date: "2025-02-18",
		ticker: "IBM",
		executive: "KAVANAUGH, JAMES J",
		executive_title: "Sr. VP and CFO",
		security_type: "Emp. Stock Option (right to buy)",
		acquisition_or_disposal: "A",
		shares: "43505.0",
		share_price: "0.0",
	},
	{
		transaction_date: "2025-02-18",
		ticker: "IBM",
		executive: "FEHRING, NICOLAS A.",
		executive_title: "VP, Controller",
		security_type: "Rst. Stock Unit",
		acquisition_or_disposal: "A",
		shares: "2787.0",
		share_price: "0.0",
	},
	{
		transaction_date: "2025-02-18",
		ticker: "IBM",
		executive: "KRISHNA, ARVIND",
		executive_title: "Director, Chairman and CEO",
		security_type: "Rst. Stock Unit",
		acquisition_or_disposal: "A",
		shares: "22659.0",
		share_price: "0.0",
	},
	{
		transaction_date: "2025-02-18",
		ticker: "IBM",
		executive: "KRISHNA, ARVIND",
		executive_title: "Director, Chairman and CEO",
		security_type: "Emp. Stock Option (right to buy)",
		acquisition_or_disposal: "A",
		shares: "90634.0",
		share_price: "0.0",
	},
	{
		transaction_date: "2025-02-18",
		ticker: "IBM",
		executive: "COHN, GARY D",
		executive_title: "Vice Chairman",
		security_type: "Rst. Stock Unit",
		acquisition_or_disposal: "A",
		shares: "9290.0",
		share_price: "0.0",
	},
	{
		transaction_date: "2025-02-18",
		ticker: "IBM",
		executive: "COHN, GARY D",
		executive_title: "Vice Chairman",
		security_type: "Emp. Stock Option (right to buy)",
		acquisition_or_disposal: "A",
		shares: "37160.0",
		share_price: "0.0",
	},
	{
		transaction_date: "2025-02-11",
		ticker: "IBM",
		executive: "THOMAS, ROBERT DAVID",
		executive_title: "Senior Vice President",
		security_type: "Common Stock",
		acquisition_or_disposal: "A",
		shares: "14714.0",
		share_price: "0.0",
	},
	{
		transaction_date: "2025-02-11",
		ticker: "IBM",
		executive: "THOMAS, ROBERT DAVID",
		executive_title: "Senior Vice President",
		security_type: "Common Stock",
		acquisition_or_disposal: "D",
		shares: "7423.0",
		share_price: "253.705",
	},
	{
		transaction_date: "2025-02-11",
		ticker: "IBM",
		executive: "THOMAS, ROBERT DAVID",
		executive_title: "Senior Vice President",
		security_type: "Rst. Stock Unit",
		acquisition_or_disposal: "D",
		shares: "14714.0",
		share_price: "0.0",
	},
	{
		transaction_date: "2025-02-10",
		ticker: "IBM",
		executive: "KAVANAUGH, JAMES J",
		executive_title: "Sr. VP and CFO",
		security_type: "Phantom Stock Unit",
		acquisition_or_disposal: "A",
		shares: "68.0",
		share_price: "0.0",
	},
	{
		transaction_date: "2025-02-10",
		ticker: "IBM",
		executive: "THOMAS, ROBERT DAVID",
		executive_title: "Senior Vice President",
		security_type: "Phantom Stock Unit",
		acquisition_or_disposal: "A",
		shares: "1.0",
		share_price: "0.0",
	},
	{
		transaction_date: "2025-02-10",
		ticker: "IBM",
		executive: "KRISHNA, ARVIND",
		executive_title: "Director, Chairman and CEO",
		security_type: "Phantom Stock Unit",
		acquisition_or_disposal: "A",
		shares: "129.0",
		share_price: "0.0",
	},
	{
		transaction_date: "2025-02-01",
		ticker: "IBM",
		executive: "FEHRING, NICOLAS A.",
		executive_title: "VP, Controller",
		security_type: "Common Stock",
		acquisition_or_disposal: "D",
		shares: "906.0",
		share_price: "254.555",
	},
	{
		transaction_date: "2025-02-01",
		ticker: "IBM",
		executive: "ROBINSON, ANNE",
		executive_title: "Senior Vice President",
		security_type: "Common Stock",
		acquisition_or_disposal: "D",
		shares: "1100.0",
		share_price: "254.555",
	},
	{
		transaction_date: "2025-02-01",
		ticker: "IBM",
		executive: "ROBINSON, ANNE",
		executive_title: "Senior Vice President",
		security_type: "Common Stock",
		acquisition_or_disposal: "A",
		shares: "2679.0",
		share_price: "0.0",
	},
	{
		transaction_date: "2025-02-01",
		ticker: "IBM",
		executive: "THOMAS, ROBERT DAVID",
		executive_title: "Senior Vice President",
		security_type: "Common Stock",
		acquisition_or_disposal: "D",
		shares: "14244.0",
		share_price: "254.555",
	},
	{
		transaction_date: "2025-02-01",
		ticker: "IBM",
		executive: "THOMAS, ROBERT DAVID",
		executive_title: "Senior Vice President",
		security_type: "Common Stock",
		acquisition_or_disposal: "A",
		shares: "29337.0",
		share_price: "0.0",
	},
	{
		transaction_date: "2025-02-01",
		ticker: "IBM",
		executive: "LAMOREAUX, NICKLE JACLYN",
		executive_title: "Senior Vice President",
		security_type: "Common Stock",
		acquisition_or_disposal: "A",
		shares: "14683.0",
		share_price: "0.0",
	},
	{
		transaction_date: "2025-02-01",
		ticker: "IBM",
		executive: "LAMOREAUX, NICKLE JACLYN",
		executive_title: "Senior Vice President",
		security_type: "Common Stock",
		acquisition_or_disposal: "D",
		shares: "7496.0",
		share_price: "254.555",
	},
	{
		transaction_date: "2025-02-01",
		ticker: "IBM",
		executive: "LAMOREAUX, NICKLE JACLYN",
		executive_title: "Senior Vice President",
		security_type: "Common Stock",
		acquisition_or_disposal: "A",
		shares: "11735.0",
		share_price: "0.0",
	},
	{
		transaction_date: "2025-02-01",
		ticker: "IBM",
		executive: "LAMOREAUX, NICKLE JACLYN",
		executive_title: "Senior Vice President",
		security_type: "Common Stock",
		acquisition_or_disposal: "D",
		shares: "5446.0",
		share_price: "254.555",
	},
	{
		transaction_date: "2025-02-01",
		ticker: "IBM",
		executive: "KRISHNA, ARVIND",
		executive_title: "Director, Chairman and CEO",
		security_type: "Common Stock",
		acquisition_or_disposal: "A",
		shares: "57626.0",
		share_price: "0.0",
	},
	{
		transaction_date: "2025-02-01",
		ticker: "IBM",
		executive: "KRISHNA, ARVIND",
		executive_title: "Director, Chairman and CEO",
		security_type: "Common Stock",
		acquisition_or_disposal: "D",
		shares: "28249.0",
		share_price: "254.555",
	},
	{
		transaction_date: "2025-02-01",
		ticker: "IBM",
		executive: "KAVANAUGH, JAMES J",
		executive_title: "Sr. VP and CFO",
		security_type: "Common Stock",
		acquisition_or_disposal: "A",
		shares: "37719.0",
		share_price: "0.0",
	},
	{
		transaction_date: "2025-02-01",
		ticker: "IBM",
		executive: "KAVANAUGH, JAMES J",
		executive_title: "Sr. VP and CFO",
		security_type: "Common Stock",
		acquisition_or_disposal: "D",
		shares: "18336.0",
		share_price: "254.555",
	},
	{
		transaction_date: "2025-02-01",
		ticker: "IBM",
		executive: "FEHRING, NICOLAS A.",
		executive_title: "VP, Controller",
		security_type: "Common Stock",
		acquisition_or_disposal: "A",
		shares: "2445.0",
		share_price: "0.0",
	},
	{
		transaction_date: "2025-02-01",
		ticker: "IBM",
		executive: "COHN, GARY D",
		executive_title: "Vice Chairman",
		security_type: "Common Stock",
		acquisition_or_disposal: "D",
		shares: "16803.0",
		share_price: "254.555",
	},
	{
		transaction_date: "2025-02-01",
		ticker: "IBM",
		executive: "COHN, GARY D",
		executive_title: "Vice Chairman",
		security_type: "Common Stock",
		acquisition_or_disposal: "A",
		shares: "30385.0",
		share_price: "0.0",
	},
	{
		transaction_date: "2025-01-04",
		ticker: "IBM",
		executive: "COHN, GARY D",
		executive_title: "Vice Chairman",
		security_type: "Common Stock",
		acquisition_or_disposal: "A",
		shares: "5114.0",
		share_price: "0.0",
	},
	{
		transaction_date: "2025-01-04",
		ticker: "IBM",
		executive: "COHN, GARY D",
		executive_title: "Vice Chairman",
		security_type: "Common Stock",
		acquisition_or_disposal: "D",
		shares: "2197.0",
		share_price: "222.075",
	},
	{
		transaction_date: "2025-01-04",
		ticker: "IBM",
		executive: "COHN, GARY D",
		executive_title: "Vice Chairman",
		security_type: "Rst. Stock Unit",
		acquisition_or_disposal: "D",
		shares: "5114.0",
		share_price: "0.0",
	},
	{
		transaction_date: "2024-12-31",
		ticker: "IBM",
		executive: "MIEBACH, MICHAEL",
		executive_title: "Director",
		security_type: "Promised Fee Share",
		acquisition_or_disposal: "A",
		shares: "399.0",
		share_price: "219.83",
	},
	{
		transaction_date: "2024-12-31",
		ticker: "IBM",
		executive: "POLLACK, MARTHA E",
		executive_title: "Director",
		security_type: "Promised Fee Share",
		acquisition_or_disposal: "A",
		shares: "251.0",
		share_price: "219.83",
	},
	{
		transaction_date: "2024-12-31",
		ticker: "IBM",
		executive: "FARR, DAVID N",
		executive_title: "Director",
		security_type: "Promised Fee Share",
		acquisition_or_disposal: "A",
		shares: "251.0",
		share_price: "219.83",
	},
	{
		transaction_date: "2024-12-31",
		ticker: "IBM",
		executive: "VOSER, PETER R.",
		executive_title: "Director",
		security_type: "Promised Fee Share",
		acquisition_or_disposal: "A",
		shares: "433.0",
		share_price: "219.83",
	},
	{
		transaction_date: "2024-12-31",
		ticker: "IBM",
		executive: "GORSKY, ALEX",
		executive_title: "Director",
		security_type: "Promised Fee Share",
		acquisition_or_disposal: "A",
		shares: "455.0",
		share_price: "219.83",
	},
	{
		transaction_date: "2024-12-31",
		ticker: "IBM",
		executive: "WADDELL, FREDERICK H",
		executive_title: "Director",
		security_type: "Promised Fee Share",
		acquisition_or_disposal: "A",
		shares: "421.0",
		share_price: "219.83",
	},
	{
		transaction_date: "2024-12-31",
		ticker: "IBM",
		executive: "BUBERL, THOMAS",
		executive_title: "Director",
		security_type: "Promised Fee Share",
		acquisition_or_disposal: "A",
		shares: "399.0",
		share_price: "219.83",
	},
	{
		transaction_date: "2024-12-31",
		ticker: "IBM",
		executive: "BROWN, MARIANNE CATHERINE",
		executive_title: "Director",
		security_type: "Promised Fee Share",
		acquisition_or_disposal: "A",
		shares: "399.0",
		share_price: "219.83",
	},
	{
		transaction_date: "2024-12-31",
		ticker: "IBM",
		executive: "ZOLLAR, ALFRED W",
		executive_title: "Director",
		security_type: "Promised Fee Share",
		acquisition_or_disposal: "A",
		shares: "399.0",
		share_price: "219.83",
	},
	{
		transaction_date: "2024-12-31",
		ticker: "IBM",
		executive: "HOWARD, MICHELLE J",
		executive_title: "Director",
		security_type: "Promised Fee Share",
		acquisition_or_disposal: "A",
		shares: "359.0",
		share_price: "219.83",
	},
	{
		transaction_date: "2024-12-31",
		ticker: "IBM",
		executive: "LIVERIS, ANDREW N",
		executive_title: "Director",
		security_type: "Promised Fee Share",
		acquisition_or_disposal: "A",
		shares: "421.0",
		share_price: "219.83",
	},
	{
		transaction_date: "2024-12-31",
		ticker: "IBM",
		executive: "MCNABB, FREDERICK WILLIAM III",
		executive_title: "Director",
		security_type: "Promised Fee Share",
		acquisition_or_disposal: "A",
		shares: "399.0",
		share_price: "219.83",
	},
	{
		transaction_date: "2024-11-13",
		ticker: "IBM",
		executive: "ZOLLAR, ALFRED W",
		executive_title: "Director",
		security_type: "Common Stock",
		acquisition_or_disposal: "A",
		shares: "936.0",
		share_price: "210.6185",
	},
	{
		transaction_date: "2024-11-12",
		ticker: "IBM",
		executive: "KAVANAUGH, JAMES J",
		executive_title: "Sr. VP and CFO",
		security_type: "Phantom Stock Unit",
		acquisition_or_disposal: "A",
		shares: "80.0",
		share_price: "0.0",
	},
	{
		transaction_date: "2024-11-12",
		ticker: "IBM",
		executive: "KRISHNA, ARVIND",
		executive_title: "Director, Chairman and CEO",
		security_type: "Phantom Stock Unit",
		acquisition_or_disposal: "A",
		shares: "151.0",
		share_price: "0.0",
	},
	{
		transaction_date: "2024-11-12",
		ticker: "IBM",
		executive: "THOMAS, ROBERT DAVID",
		executive_title: "Senior Vice President",
		security_type: "Phantom Stock Unit",
		acquisition_or_disposal: "A",
		shares: "1.0",
		share_price: "0.0",
	},
	{
		transaction_date: "2024-11-08",
		ticker: "IBM",
		executive: "LAMOREAUX, NICKLE JACLYN",
		executive_title: "Senior Vice President",
		security_type: "Common Stock",
		acquisition_or_disposal: "D",
		shares: "3600.0",
		share_price: "215.202",
	},
	{
		transaction_date: "2024-09-30",
		ticker: "IBM",
		executive: "GORSKY, ALEX",
		executive_title: "Director",
		security_type: "Promised Fee Share",
		acquisition_or_disposal: "A",
		shares: "453.0",
		share_price: "221.08",
	},
	{
		transaction_date: "2024-09-30",
		ticker: "IBM",
		executive: "FARR, DAVID N",
		executive_title: "Director",
		security_type: "Promised Fee Share",
		acquisition_or_disposal: "A",
		shares: "250.0",
		share_price: "221.08",
	},
	{
		transaction_date: "2024-09-30",
		ticker: "IBM",
		executive: "BUBERL, THOMAS",
		executive_title: "Director",
		security_type: "Promised Fee Share",
		acquisition_or_disposal: "A",
		shares: "396.0",
		share_price: "221.08",
	},
	{
		transaction_date: "2024-09-30",
		ticker: "IBM",
		executive: "BROWN, MARIANNE CATHERINE",
		executive_title: "Director",
		security_type: "Promised Fee Share",
		acquisition_or_disposal: "A",
		shares: "396.0",
		share_price: "221.08",
	},
	{
		transaction_date: "2024-09-30",
		ticker: "IBM",
		executive: "HOWARD, MICHELLE J",
		executive_title: "Director",
		security_type: "Promised Fee Share",
		acquisition_or_disposal: "A",
		shares: "357.0",
		share_price: "221.08",
	},
	{
		transaction_date: "2024-09-30",
		ticker: "IBM",
		executive: "VOSER, PETER R.",
		executive_title: "Director",
		security_type: "Promised Fee Share",
		acquisition_or_disposal: "A",
		shares: "430.0",
		share_price: "221.08",
	},
	{
		transaction_date: "2024-09-30",
		ticker: "IBM",
		executive: "POLLACK, MARTHA E",
		executive_title: "Director",
		security_type: "Promised Fee Share",
		acquisition_or_disposal: "A",
		shares: "250.0",
		share_price: "221.08",
	},
	{
		transaction_date: "2024-09-30",
		ticker: "IBM",
		executive: "MIEBACH, MICHAEL",
		executive_title: "Director",
		security_type: "Promised Fee Share",
		acquisition_or_disposal: "A",
		shares: "396.0",
		share_price: "221.08",
	},
	{
		transaction_date: "2024-09-30",
		ticker: "IBM",
		executive: "MCNABB, FREDERICK WILLIAM III",
		executive_title: "Director",
		security_type: "Promised Fee Share",
		acquisition_or_disposal: "A",
		shares: "396.0",
		share_price: "221.08",
	},
	{
		transaction_date: "2024-09-30",
		ticker: "IBM",
		executive: "ZOLLAR, ALFRED W",
		executive_title: "Director",
		security_type: "Promised Fee Share",
		acquisition_or_disposal: "A",
		shares: "396.0",
		share_price: "221.08",
	},
	{
		transaction_date: "2024-09-30",
		ticker: "IBM",
		executive: "WADDELL, FREDERICK H",
		executive_title: "Director",
		security_type: "Promised Fee Share",
		acquisition_or_disposal: "A",
		shares: "419.0",
		share_price: "221.08",
	},
	{
		transaction_date: "2024-09-30",
		ticker: "IBM",
		executive: "LIVERIS, ANDREW N",
		executive_title: "Director",
		security_type: "Promised Fee Share",
		acquisition_or_disposal: "A",
		shares: "419.0",
		share_price: "221.08",
	},
	{
		transaction_date: "2024-09-03",
		ticker: "IBM",
		executive: "FEHRING, NICOLAS A.",
		executive_title: "VP, Controller",
		security_type: "Common Stock",
		acquisition_or_disposal: "D",
		shares: "530.0",
		share_price: "0.0",
	},
	{
		transaction_date: "2024-09-01",
		ticker: "IBM",
		executive: "FEHRING, NICOLAS A.",
		executive_title: "VP, Controller",
		security_type: "Rst. Stock Unit",
		acquisition_or_disposal: "D",
		shares: "2742.0",
		share_price: "0.0",
	},
	{
		transaction_date: "2024-09-01",
		ticker: "IBM",
		executive: "LAMOREAUX, NICKLE JACLYN",
		executive_title: "Senior Vice President",
		security_type: "Common Stock",
		acquisition_or_disposal: "D",
		shares: "978.0",
		share_price: "200.475",
	},
	{
		transaction_date: "2024-09-01",
		ticker: "IBM",
		executive: "LAMOREAUX, NICKLE JACLYN",
		executive_title: "Senior Vice President",
		security_type: "Common Stock",
		acquisition_or_disposal: "A",
		shares: "1915.0",
		share_price: "0.0",
	},
	{
		transaction_date: "2024-09-01",
		ticker: "IBM",
		executive: "FEHRING, NICOLAS A.",
		executive_title: "VP, Controller",
		security_type: "Common Stock",
		acquisition_or_disposal: "D",
		shares: "1388.0",
		share_price: "200.475",
	},
	{
		transaction_date: "2024-09-01",
		ticker: "IBM",
		executive: "LAMOREAUX, NICKLE JACLYN",
		executive_title: "Senior Vice President",
		security_type: "Rst. Stock Unit",
		acquisition_or_disposal: "D",
		shares: "1915.0",
		share_price: "0.0",
	},
	{
		transaction_date: "2024-09-01",
		ticker: "IBM",
		executive: "FEHRING, NICOLAS A.",
		executive_title: "VP, Controller",
		security_type: "Common Stock",
		acquisition_or_disposal: "A",
		shares: "2742.0",
		share_price: "0.0",
	},
	{
		transaction_date: "2024-08-09",
		ticker: "IBM",
		executive: "KRISHNA, ARVIND",
		executive_title: "Director, Chairman and CEO",
		security_type: "Phantom Stock Unit",
		acquisition_or_disposal: "A",
		shares: "165.0",
		share_price: "0.0",
	},
	{
		transaction_date: "2024-08-09",
		ticker: "IBM",
		executive: "THOMAS, ROBERT DAVID",
		executive_title: "Senior Vice President",
		security_type: "Phantom Stock Unit",
		acquisition_or_disposal: "A",
		shares: "1.0",
		share_price: "0.0",
	},
	{
		transaction_date: "2024-08-09",
		ticker: "IBM",
		executive: "KAVANAUGH, JAMES J",
		executive_title: "Sr. VP and CFO",
		security_type: "Phantom Stock Unit",
		acquisition_or_disposal: "A",
		shares: "88.0",
		share_price: "0.0",
	},
	{
		transaction_date: "2024-07-01",
		ticker: "IBM",
		executive: "ROBINSON, ANNE",
		executive_title: "Senior Vice President",
		security_type: "Rst. Stock Unit",
		acquisition_or_disposal: "A",
		shares: "20592.0",
		share_price: "0.0",
	},
	{
		transaction_date: "2024-07-01",
		ticker: "IBM",
		executive: "ROBINSON, ANNE",
		executive_title: "Senior Vice President",
		security_type: "Rst. Stock Unit",
		acquisition_or_disposal: "A",
		shares: "5648.0",
		share_price: "0.0",
	},
	{
		transaction_date: "2024-07-01",
		ticker: "IBM",
		executive: "ROBINSON, ANNE",
		executive_title: "Senior Vice President",
		security_type: "Emp. Stock Option (right to buy)",
		acquisition_or_disposal: "A",
		shares: "28240.0",
		share_price: "0.0",
	},
	{
		transaction_date: "2024-06-28",
		ticker: "IBM",
		executive: "BROWN, MARIANNE CATHERINE",
		executive_title: "Director",
		security_type: "Promised Fee Share",
		acquisition_or_disposal: "A",
		shares: "506.0",
		share_price: "172.95",
	},
	{
		transaction_date: "2024-06-28",
		ticker: "IBM",
		executive: "BUBERL, THOMAS",
		executive_title: "Director",
		security_type: "Promised Fee Share",
		acquisition_or_disposal: "A",
		shares: "506.0",
		share_price: "172.95",
	},
	{
		transaction_date: "2024-06-28",
		ticker: "IBM",
		executive: "LIVERIS, ANDREW N",
		executive_title: "Director",
		security_type: "Promised Fee Share",
		acquisition_or_disposal: "A",
		shares: "535.0",
		share_price: "172.95",
	},
	{
		transaction_date: "2024-06-28",
		ticker: "IBM",
		executive: "MCNABB, FREDERICK WILLIAM III",
		executive_title: "Director",
		security_type: "Promised Fee Share",
		acquisition_or_disposal: "A",
		shares: "506.0",
		share_price: "172.95",
	},
	{
		transaction_date: "2024-06-28",
		ticker: "IBM",
		executive: "MIEBACH, MICHAEL",
		executive_title: "Director",
		security_type: "Promised Fee Share",
		acquisition_or_disposal: "A",
		shares: "506.0",
		share_price: "172.95",
	},
	{
		transaction_date: "2024-06-28",
		ticker: "IBM",
		executive: "POLLACK, MARTHA E",
		executive_title: "Director",
		security_type: "Promised Fee Share",
		acquisition_or_disposal: "A",
		shares: "319.0",
		share_price: "172.95",
	},
	{
		transaction_date: "2024-06-28",
		ticker: "IBM",
		executive: "VOSER, PETER R.",
		executive_title: "Director",
		security_type: "Promised Fee Share",
		acquisition_or_disposal: "A",
		shares: "550.0",
		share_price: "172.95",
	},
	{
		transaction_date: "2024-06-28",
		ticker: "IBM",
		executive: "WADDELL, FREDERICK H",
		executive_title: "Director",
		security_type: "Promised Fee Share",
		acquisition_or_disposal: "A",
		shares: "535.0",
		share_price: "172.95",
	},
	{
		transaction_date: "2024-06-28",
		ticker: "IBM",
		executive: "ZOLLAR, ALFRED W",
		executive_title: "Director",
		security_type: "Promised Fee Share",
		acquisition_or_disposal: "A",
		shares: "506.0",
		share_price: "172.95",
	},
	{
		transaction_date: "2024-06-28",
		ticker: "IBM",
		executive: "HOWARD, MICHELLE J",
		executive_title: "Director",
		security_type: "Promised Fee Share",
		acquisition_or_disposal: "A",
		shares: "456.0",
		share_price: "172.95",
	},
	{
		transaction_date: "2024-06-28",
		ticker: "IBM",
		executive: "GORSKY, ALEX",
		executive_title: "Director",
		security_type: "Promised Fee Share",
		acquisition_or_disposal: "A",
		shares: "579.0",
		share_price: "172.95",
	},
]};
