export const stockNames = [
    "NKLA",
    "IBIO",
    "VERB",
    "GMDA",
    "SOXS",
    "CCL",
    "SQQQ",
    "CISS",
    "NIO",
    // "TSLA",
    // "SPY",
    // "TLRY",
    // "MARA",
    // "NVDA",
    // "SOXL",
    // "TQQQ",
    // "AMD",
    // "CGC",
    // "IBIT",
    // "AAPL",
    // "F",
    // "LCID",
    // "WISA",
    // "SOUN",
    // "INTC",
    // "MPW",
    // "PLTR",
    // "QQQ",
    // "XPEV",
    // "PLUG",
    // "XLF",
    // "TLT",
    // "RIVN",
    // "SOFI",
    // "TZA",
    // "DJT",
    // "CLSK",
    // "LIXT",
    // "T",
    // "JAGX",
    // "HOOD",
    // "IWM",
    // "DKNG",
    // "BAC",
    // "LQD",
    // "MRDB",
    // "BITF",
    // "GOLD",
    // "WKHS",
    // "PFE",
    // "ROIV",
    // "NU",
    // "HYG",
    // "BITO",
    // "RUN",
    // "TELL",
    // "AMZN",
    // "CZOO",
    // "DNUT",
    // "WBD",
    // "WULF",
    // "MU",
    // "GDX",
    // "OTRK",
    // "AAL",
    // "VALE",
    // "BBD",
    // "KULR",
    // "MRVL",
    // "GM",
    // "FFIE",
    // "NYCB",
    // "EEM",
    // "GEVO",
    // "GOOGL",
    // "SPXU",
    // "RIOT",
    // "GRAB",
    // "GME",
    // "KWEB",
    // "BCS",
    // "SPXS",
    // "STOK",
    // "UVXY",
    // "NVDL",
    // "SNDL",
    // "RDDT",
    // "NCLH",
    // "PCG",
    // "FXI",
    // "SMR",
    // "VLD",
    // "EGOX",
    // "TNA",
    // "XLE",
    // "PARA",
    // "CHPT",
    // "LYFT",
    // "JD",
    // "BOIL",
  ];